### ISSUE TITLE
Use OpenDNS instead of Google's DNS

### ISSUE THREAD

**Issue by noplanman** [pparent76/Own-Mailbox_debian_install#10]
Not sure if it's possible, but it should work to use the [OpenDNS](https://www.opendns.com/) servers instead of Google, considering that this project is all about privacy and dark web etc.

`208.67.222.222` and `208.67.220.220`

**Comment by pparent76** [comment]
OpenDNS do not implement DNSsec, and lie about DNS that do not exist, or that they filter. So that won't make it.

**Comment by noplanman** [comment]
That's unfortunate, but ok.
