### ISSUE TITLE
Fix Docker capabilities

### ISSUE THREAD

**Issue by dashohoxha** [pparent76/Own-Mailbox_debian_install#13]
An extensive doc that explains the docker capabilities and privileges: 
https://docs.docker.com/engine/reference/run/#/runtime-privilege-and-linux-capabilities

**Comment by pparent76** [comment]
Hi,

Concerning iptables privileges, I did not do it yet, because iptables rules should not apply to host system. (It would be very problematic since it would then only be able to access tor and the local network).

I think we would need to do a specific iptables configuration for docker.

What do you think about it?

Thank's
Pierre.

**Comment by dashohoxha** [comment]
Look at this example:
- https://github.com/docker-build/bind9/blob/master/ufw.sh
- https://github.com/docker-build/bind9/blob/master/run.sh

Maybe it is a bit complicated for you to understand. Even I have troubles trying to understand it now, a few years later. But the important point is that when I run `iptables-save` inside the container I get the output that is normally produced by the script `ufw.sh` above. However when I run `iptables-save` on the host I get a totally different output. This indicates that the firewall rules of the container are independent from the firewall rules of the host, there is a separation between them, they are not mixed together.

Does it seem counterintuitive? Maybe, but I think it is only logical, it is exactly how it should work. The container is supposed to isolate the guest system from the host system. Why do you think it cannot do this for the firewall rules?

**Comment by dashohoxha** [comment]
Sorry, I forgot to answer your question.
I don't think we need to do a specific iptables configuration for the docker. If in dought, give it a try and find it out. Did you try it already?

**Comment by pparent76** [comment]
Ok I will try as soon as I have time
