### ISSUE TITLE
Error while setting up mailpile.

### ISSUE THREAD

**Issue by dashohoxha** [pparent76/Own-Mailbox_debian_install#2]
> ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting
> ---
> 
> Cleaning up...
> Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-MlIsXE/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-2hmDg0-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-MlIsXE/pillow
> Storing debug log for failure in /root/.pip/pip.log
> Error while setting up mailpile.

**Comment by pparent76** [comment]
Ok Sorry there where some packages required, that where not installed by the script, (but that are installed by default on Raspberry pi image, and some other debian images).

I committed a patch.

Can you do a git pull and retry?

**Comment by dashohoxha** [comment]
> Can you do a git pull and retry?

Sure. But I have also created a PR with the steps that I do to test it (with docker), so that you can also try it and see if anything else is missing.
