### ISSUE TITLE
Create organization Own-Mailbox

### ISSUE THREAD

**Issue by dashohoxha** [pparent76/Own-Mailbox_debian_install#4]
Why don't you create an GitHub organization, named Own-Mailbox, and then put all the related projects in it (for example debian_install). For example I have created this one for one of my projects: https://github.com/B-Translator/

This is not neccessary, but it can help with better organization of the work.

**Comment by noplanman** [comment]
Just saw this issue and thought it would make sense, as there are a few repos now, all prefixed with **Omb-**.

But as @dashohoxha mentions, it is not necessary but easier to manage.

**Comment by pparent76** [comment]
Yes I do agree, I only had very few time to look how to do this.

**Comment by dashohoxha** [comment]
It is actually very simple and should not take a long time.
I can do it for you, if you agree. Just takes a few renaming and
find-replace operations. I do things like this all the time.

**Comment by dashohoxha** [comment]
@pparent76  I have created this organization: https://github.com/Own-Mailbox
Once you join it, I can make you Owner.

I have also forked and renamed some repositories.
But I did not fork debstrap and ihm yet, because they have pending pull requests.
Once you merge them, you can do the fork and rename yourself.

I think that a find-replace needs to be done on all repositories, in order to delete the prefix 'Omb-' and to rename the url of the git repositories.

Finally, once everything is tested, you can delete the old repositories from pparent76.

**Comment by noplanman** [comment]
@dashohoxha Wouldn't Pierre need to rename/move his repositories to the Own-Mailbox organisation instead of creating a fork of them? If it's just a fork and he deletes his repos, wouldn't all issues and PRs history go lost?

I've never done this so I'm learning.

**Comment by dashohoxha** [comment]
Forking is a way to copy a repo to another workspace (organization), and then you can rename it.
Yes, issues and PRs get lost in this process.

But you can request GitHub support to do the moving for you, and then PR and issues will be preserved as well. Try it, GitHub support is very responsive.

You can also delete the repos that I forked and have the GitHub support move them, if their PR and issue history is important.

**Comment by noplanman** [comment]
Ok I understand, thanks for explaining.

**Comment by pparent76** [comment]
I will handle that as soon as I have finished testing pull requests (my time is limited these days).

**Comment by pparent76** [comment]
Just to tell that I've not forgotten it I will do the switch (maybe in a month or so).

**Comment by dashohoxha** [comment]
Done.
The old repos remain to be deleted.
